
<div id="owl-hero" class="owl-carousel owl-theme">
    <div class="">
        <div class="hero-title">
            <h1>Welcome to PodSix Theme</h1>
            <p>Mauris aliquet vel ultrices scelerisque nulla tellus convallis sed dictumst.</p>
            <a href="<?php echo $this->getUrl('#'); ?>">
                <button class="secondary"><span>Shop Now</span></button>
            </a>
        </div>
        <img src='<?php echo $this->getViewFileUrl('images/hp-hero.jpg'); ?>' alt="Hands Typing On Keyboard">

    </div>
    <div class="">
        <div class="hero-title">
            <h1>Welcome to PodSix Theme</h1>
            <p>Mauris aliquet vel ultrices scelerisque nulla tellus convallis sed dictumst.</p>
            <a href="<?php echo $this->getUrl('#'); ?>">
                <button class="secondary"><span>Shop Now</span></button>
            </a>
        </div>
        <img src='<?php echo $this->getViewFileUrl('images/hp-hero.jpg'); ?>' alt="Hands Typing On Keyboard">

    </div>
</div>


<div class="container-fluid hp-intro">
    <div class="row">
        <div class="col-lg-4 col-md-4 text-center">
            <img src='<?php echo $this->getViewFileUrl('images/placeholder.jpg'); ?>' alt="Placeholder Image">
            <h2>Intro 1</h2>
            <p>Mauris aliquet vel ultrices scelerisque nulla tellus convallis sed dictumst.</p>
        </div>
        <div class="col-lg-4 col-md-4 text-center">
            <img src='<?php echo $this->getViewFileUrl('images/placeholder.jpg'); ?>' alt="Placeholder Image">
            <h2>Intro 2</h2>
            <p>Mauris aliquet vel ultrices scelerisque nulla tellus convallis sed dictumst.</p>
        </div>
        <div class="col-lg-4 col-md-4 text-center">
            <img src='<?php echo $this->getViewFileUrl('images/placeholder.jpg'); ?>' alt="Placeholder Image">
            <h2>Intro 3</h2>
            <p>Mauris aliquet vel ultrices scelerisque nulla tellus convallis sed dictumst.</p>
        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 text-center">
            <h3>Owl Carousel</h3>
        </div>
        <div id="owl-carousel" class="themed-owl-carousel owl-carousel owl-theme">
            <div class="">
                <a href="#" >
                    <img src='<?php echo $this->getViewFileUrl('images/placeholder.jpg'); ?>' alt="Placeholder Image">
                </a>
            </div>
            <div class="">
                <a href="#" >
                    <img src='<?php echo $this->getViewFileUrl('images/placeholder.jpg'); ?>' alt="Placeholder Image">
                </a>
            </div>
            <div class="">
                <a href="#" >
                    <img src='<?php echo $this->getViewFileUrl('images/placeholder.jpg'); ?>' alt="Placeholder Image">
                </a>
            </div>
            <div class="">
                <a href="#" >
                    <img src='<?php echo $this->getViewFileUrl('images/placeholder.jpg'); ?>' alt="Placeholder Image">
                </a>
            </div>
            <div class="">
                <a href="#" >
                    <img src='<?php echo $this->getViewFileUrl('images/placeholder.jpg'); ?>' alt="Placeholder Image">
                </a>
            </div>
        </div>
    </div>
</div>












