<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                            echo __('') ?></span></label>
                    <script type="text/x-magento-init">
                    {
                       "*": {
                               "Magento_Ui/js/core/app": {
                                   "components": {
                                       "qty_change": {
                                           "component": "Magento_Catalog/js/view/product/view/qty_change",
                                           "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                                       }
                                   }
                               }
                       }
                    }
                    </script>

                    <div class="control" data-bind="scope: 'qty_change'">
                        <label>Qty</label>
                        <button class="decrease-quantity"
                                data-bind="click: decreaseQty"><i class="fal fa-minus"></i>
                        </button>

                        <input data-bind="value: qty()"
                               type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               title="<?php echo __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <button class="increase-quantity"
                                data-bind="click: increaseQty"><i class="fal fa-plus"></i>
                        </button>
                    </div>
                </div>

            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
