<div class="container-fluid newsletter-block">
    <div class="row p68">
        <div class="col-lg-12 col-md-12 text-center">
            <h3>Join Our Newsletter</h3>
            <p>Scelerisque eu, est dolor mattis. Diam ipsum vivamus urna ac elementum. Odio euismod aliquet pharetra dolor sit tempor cras nibh quis.</p>
        </div>
        <div class="col-lg-12 col-md-12 text-center">
            <div id="newsletter_wrapper">
                <input name="email" type="email" id="newsletter" placeholder="Enter your email address" data-validate="{required:true, 'validate-email':true}">
                <div id="newsletter_button">
                    <button title="Subscribe" type="submit" aria-label="Subscribe">Subscribe
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
