<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>

<div class="toggle-search" id="toggle-search">
    <div class="container-fluid">
    <div class="row padding-0">
        <div class="col-md-12 padding-0">
            <form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                               type="text"
                               name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                               value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                               placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
                               class="input-text"
                               maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <div class="actions">
                            <button type="submit" class="action search">
                                <i class="fal fa-search"></i>

                            </button>
                        </div>
                        <div id="close-search-toggle-trigger">
                            <i class="fal fa-times"></i>
                        </div>
                        <?= $block->getChildHtml() ?>
                    </div>
                </div>
            </form>
        </div>

    </div>
    </div>
</div>
