<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                            echo __('') ?></span></label>
                    <script type="text/x-magento-init">
                    {
                       "*": {
                               "Magento_Ui/js/core/app": {
                                   "components": {
                                       "qty_change": {
                                           "component": "Magento_Catalog/js/view/product/view/qty_change",
                                           "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                                       }
                                   }
                               }
                       }
                    }
                    </script>

                    <div class="control" data-bind="scope: 'qty_change'">
                        <label>Quantity</label>
                        <button class="decrease-quantity" data-bind="click: decreaseQty"><i
                                class="fas fa-caret-down"></i></button>
                        <input data-bind="value: qty()"
                               type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               title="<?php echo __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <button class="increase-quantity" data-bind="click: increaseQty"><i class="fas fa-caret-up"></i>
                        </button>
                    </div>
                </div>

            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>

                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
