<div class="container-fluid footer-main">
    <div class="row">
        <div class="col-lg-5 col-md-6 ">
            <div class="footer-logo">
                <img src='<?php echo $this->getViewFileUrl('images/logo-light.png'); ?>' alt="Company Logo">
            </div>
        </div>
        <div class="col-lg-2 col-md-6 col-sm-6">
            <div class="footer-nav">
                <ul>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-2 col-md-6 col-sm-6">
            <div class="footer-nav">
                <ul>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                    <li><a href="<?php echo $this->getUrl('#'); ?>">Link</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="footer-nav">
                <div class="footer-social">
                    <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
                    <a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
