<div class="container-fluid footer-bottom">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 footer-terms">
            <a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a>
            <a href="<?php echo $this->getUrl('terms-conditions'); ?>">Terms & Conditions</a>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 footer-copyright">
            <p>&copy; <?php echo date("Y"); ?> PodsixTheme. All Rights Reserved.</p>
        </div>
    </div>
</div>

