
<div class="header-main" id="header-main">
    <?php echo $block->getChildHtml('toggle.search'); ?>
    <div class="header content">
        <!-- Scroll to top button -->
        <a href="javascript:" id="return-to-top"><i class="fal fa-chevron-up"></i></a>
        <div class="row">

            <!-- Header Left -->
            <div class="col-md-4 col-sm-6">
                <?php echo $this->getChildHtml("logo"); ?>
                <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */
                        echo __('Toggle Nav') ?></span></span>
            </div>

            <!-- Header Center -->
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="header-center">
                        <?php echo $block->getChildHtml('top.search'); ?>

                    </div>
            </div>

            <!-- Header Right -->
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="header-right">
                    <?php echo $block->getChildHtml('header.icons'); ?>
                    <?php echo $block->getChildHtml('minicart'); ?>
                </div>
            </div>
        </div>
    </div>


    <!-- Header Bottom NAV-->
    <?php echo $this->getChildHtml("navigation.sections"); ?>



</div>




